block.settings.menu_block_current_language:*:
  type: block_settings
  label: 'Menu block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
    translation_providers:
      type: sequence
      label: 'Enabled translation providers'
      sequence:
        type: string
        label: 'Provider'
